name: ritajade
favicon: null
layout_spectrum: 0.87652
typography_spectrum: 0.789120152592659
title: Empowered Life with Rita Jade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8506767628714442
  lightness: 0.6571225563529879
  saturation: 0.10314032435417175
  rhythmicContrast: 0.6896141797769815
purpose: []
